export type ResistanceLevel = "excellent" | "good" | "limited";

export type ChemicalResistanceItem = {
  substance: string;
  pvcU: string;
  cpvc: string;
  resistance: ResistanceLevel;
};

const toResistanceLevel = (value: string): ResistanceLevel => {
  switch (value) {
    case "Excelente":
      return "excellent";
    case "Bom":
      return "good";
    case "Limitado":
      return "limited";
    default:
      return "limited";
  }
};

const rawChemicalResistanceData = [
  ["Ácido Acético (CH3COOH) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Acético (CH3COOH) 50%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Acético (CH3COOH) 99%", "Bom", "Excelente", "Bom"],
  ["Ácido Acético Glacial", "Bom", "Excelente", "Bom"],
  ["Ácido Bórico (H3BO3)", "Excelente", "Excelente", "Excelente"],
  ["Ácido Carbônico (H2CO3)", "Excelente", "Excelente", "Excelente"],
  ["Ácido Cítrico (C6H8O7) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Cítrico (C6H8O7) Saturado", "Excelente", "Excelente", "Excelente"],
  ["Ácido Clorídrico (HCl) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Clorídrico (HCl) 20%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Clorídrico (HCl) 37%", "Bom", "Excelente", "Bom"],
  ["Ácido Crômico (H2CrO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Crômico (H2CrO4) 50%", "Bom", "Excelente", "Bom"],
  ["Ácido Fluorídrico (HF) 20%", "Limitado", "Limitado", "Limitado"],
  ["Ácido Fluorídrico (HF) 40%", "Limitado", "Limitado", "Limitado"],
  ["Ácido Fosfórico (H3PO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Fosfórico (H3PO4) 30%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Fosfórico (H3PO4) 85%", "Bom", "Excelente", "Bom"],
  ["Ácido Fórmico (HCOOH) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Fórmico (HCOOH) 50%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Láctico (C3H6O3) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Láctico (C3H6O3) 50%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Nítrico (HNO3) 10%", "Bom", "Excelente", "Bom"],
  ["Ácido Nítrico (HNO3) 30%", "Bom", "Excelente", "Bom"],
  ["Ácido Nítrico (HNO3) 50%", "Limitado", "Bom", "Limitado"],
  ["Ácido Nítrico (HNO3) 65%", "Limitado", "Bom", "Limitado"],
  ["Ácido Oxálico (C2H2O4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Oxálico (C2H2O4) Saturado", "Excelente", "Excelente", "Excelente"],
  ["Ácido Sulfúrico (H2SO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Sulfúrico (H2SO4) 30%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Sulfúrico (H2SO4) 50%", "Bom", "Excelente", "Bom"],
  ["Ácido Sulfúrico (H2SO4) 75%", "Bom", "Excelente", "Bom"],
  ["Ácido Sulfúrico (H2SO4) 93%", "Limitado", "Bom", "Limitado"],
  ["Ácido Sulfuroso (H2SO3) 10%", "Excelente", "Excelente", "Excelente"],
  ["Ácido Tânico (C76H52O46)", "Excelente", "Excelente", "Excelente"],
  ["Ácido Tartárico (C4H6O6)", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Amônio (NH4OH) 10%", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Amônio (NH4OH) 30%", "Bom", "Excelente", "Bom"],
  ["Hidróxido de Cálcio (Ca(OH)2) Saturado", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Potássio (KOH) 10%", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Potássio (KOH) 50%", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Sódio (NaOH) 10%", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Sódio (NaOH) 30%", "Excelente", "Excelente", "Excelente"],
  ["Hidróxido de Sódio (NaOH) 50%", "Excelente", "Excelente", "Excelente"],
  ["Alúmen (KAl(SO4)2)", "Excelente", "Excelente", "Excelente"],
  ["Bicarbonato de Sódio (NaHCO3)", "Excelente", "Excelente", "Excelente"],
  ["Bissulfito de Sódio (NaHSO3)", "Excelente", "Excelente", "Excelente"],
  ["Brometo de Potássio (KBr)", "Excelente", "Excelente", "Excelente"],
  ["Carbonato de Cálcio (CaCO3)", "Excelente", "Excelente", "Excelente"],
  ["Carbonato de Sódio (Na2CO3) 10%", "Excelente", "Excelente", "Excelente"],
  ["Carbonato de Sódio (Na2CO3) 30%", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Alumínio (AlCl3) 20%", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Amônio (NH4Cl) 10%", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Cálcio (CaCl2) 30%", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Cálcio (CaCl2) Saturado", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Ferro (FeCl3) 30%", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Magnésio (MgCl2)", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Potássio (KCl) Saturado", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Sódio (NaCl) 10%", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Sódio (NaCl) Saturado", "Excelente", "Excelente", "Excelente"],
  ["Cloreto de Zinco (ZnCl2) 80%", "Excelente", "Excelente", "Excelente"],
  ["Fosfato Trissódico (Na3PO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Nitrato de Prata (AgNO3)", "Excelente", "Excelente", "Excelente"],
  ["Sulfato de Alumínio (Al2(SO4)3) 10%", "Excelente", "Excelente", "Excelente"],
  ["Sulfato de Cobre (CuSO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Sulfato de Magnésio (MgSO4)", "Excelente", "Excelente", "Excelente"],
  ["Sulfato de Níquel (NiSO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Sulfato de Sódio (Na2SO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Sulfato de Zinco (ZnSO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Tiossulfato de Sódio (Na2S2O3) 10%", "Excelente", "Excelente", "Excelente"],
  ["Água Deionizada", "Excelente", "Excelente", "Excelente"],
  ["Água Destilada", "Excelente", "Excelente", "Excelente"],
  ["Água do Mar", "Excelente", "Excelente", "Excelente"],
  ["Água Potável", "Excelente", "Excelente", "Excelente"],
  ["Água Régia (HCl + HNO3)", "Limitado", "Limitado", "Limitado"],
  ["Amônia (NH3) 10%", "Excelente", "Excelente", "Excelente"],
  ["Amônia (NH3) 30%", "Bom", "Excelente", "Bom"],
  ["Amônia Anidra (NH3)", "Bom", "Excelente", "Bom"],
  ["Bromo (Br2) Líquido", "Limitado", "Limitado", "Limitado"],
  ["Cloro (Cl2) Gasoso Seco", "Excelente", "Excelente", "Excelente"],
  ["Cloro (Cl2) Gasoso Úmido", "Bom", "Excelente", "Bom"],
  ["Cloro (Cl2) 10%", "Bom", "Excelente", "Bom"],
  ["Cloro (Cl2) Líquido", "Limitado", "Bom", "Limitado"],
  ["Dióxido de Carbono (CO2)", "Excelente", "Excelente", "Excelente"],
  ["Dióxido de Enxofre (SO2) Gasoso", "Excelente", "Excelente", "Excelente"],
  ["Ozônio (O3)", "Limitado", "Bom", "Limitado"],
  ["Hipoclorito de Cálcio (Ca(ClO)2) 10%", "Bom", "Excelente", "Bom"],
  ["Hipoclorito de Sódio (NaClO) 10%", "Bom", "Excelente", "Bom"],
  ["Hipoclorito de Sódio (NaClO) 20%", "Bom", "Excelente", "Bom"],
  ["Peróxido de Hidrogênio (H2O2) 3%", "Bom", "Excelente", "Bom"],
  ["Peróxido de Hidrogênio (H2O2) 10%", "Bom", "Excelente", "Bom"],
  ["Peróxido de Hidrogênio (H2O2) 30%", "Limitado", "Bom", "Limitado"],
  ["Permanganato de Potássio (KMnO4) 10%", "Excelente", "Excelente", "Excelente"],
  ["Álcool Amílico (C5H11OH)", "Excelente", "Excelente", "Excelente"],
  ["Álcool Butílico (C4H9OH)", "Excelente", "Excelente", "Excelente"],
  ["Álcool Isopropílico (C3H7OH) 100%", "Excelente", "Excelente", "Excelente"],
  ["Etanol (C2H5OH) 10%", "Excelente", "Excelente", "Excelente"],
  ["Etanol (C2H5OH) 50%", "Excelente", "Excelente", "Excelente"],
  ["Etanol (C2H5OH) 100%", "Excelente", "Excelente", "Excelente"],
  ["Etilenoglicol (C2H6O2)", "Excelente", "Excelente", "Excelente"],
  ["Glicerina (C3H8O3) 100%", "Excelente", "Excelente", "Excelente"],
  ["Metanol (CH3OH) 100%", "Excelente", "Excelente", "Excelente"],
  ["Acetona (C3H6O) 10%", "Bom", "Excelente", "Bom"],
  ["Acetona (C3H6O) 100%", "Limitado", "Bom", "Limitado"],
  ["Metiletilcetona (MEK) (C4H8O)", "Limitado", "Bom", "Limitado"],
  ["Metilisobutilcetona (MIBK) (C6H12O)", "Limitado", "Bom", "Limitado"],
  ["Gasolina", "Bom", "Excelente", "Bom"],
  ["Hexano (C6H14)", "Bom", "Excelente", "Bom"],
  ["Nafta", "Bom", "Excelente", "Bom"],
  ["Óleo Diesel", "Bom", "Excelente", "Bom"],
  ["Óleo Lubrificante", "Excelente", "Excelente", "Excelente"],
  ["Óleo Mineral", "Excelente", "Excelente", "Excelente"],
  ["Querosene", "Bom", "Excelente", "Bom"],
  ["Benzeno (C6H6) 100%", "Limitado", "Bom", "Limitado"],
  ["Estireno (C8H8)", "Limitado", "Limitado", "Limitado"],
  ["Tolueno (C7H8) 100%", "Limitado", "Bom", "Limitado"],
  ["Xileno (C8H10)", "Limitado", "Bom", "Limitado"],
  ["Clorofórmio (CHCl3)", "Limitado", "Limitado", "Limitado"],
  ["Diclorometano (CH2Cl2)", "Limitado", "Limitado", "Limitado"],
  ["Tetracloreto de Carbono (CCl4)", "Limitado", "Limitado", "Limitado"],
  ["Tricloroetileno (C2HCl3)", "Limitado", "Limitado", "Limitado"],
  ["Acetato de Amila (C7H14O2)", "Limitado", "Bom", "Limitado"],
  ["Acetato de Butila (C6H12O2)", "Limitado", "Bom", "Limitado"],
  ["Acetato de Etila (C4H8O2)", "Limitado", "Bom", "Limitado"],
  ["Éter Etílico (C4H10O)", "Limitado", "Bom", "Limitado"],
  ["Fenol (C6H5OH) 5%", "Excelente", "Excelente", "Excelente"],
  ["Fenol (C6H5OH) 100%", "Limitado", "Bom", "Limitado"],
  ["Cerveja", "Excelente", "Excelente", "Excelente"],
  ["Leite", "Excelente", "Excelente", "Excelente"],
  ["Óleo Vegetal", "Excelente", "Excelente", "Excelente"],
  ["Suco de Frutas", "Excelente", "Excelente", "Excelente"],
  ["Vinho", "Excelente", "Excelente", "Excelente"],
  ["Anilina (C6H7N)", "Bom", "Excelente", "Bom"],
  ["Detergentes Comerciais", "Excelente", "Excelente", "Excelente"],
  ["Formol (Formaldeído) 40%", "Excelente", "Excelente", "Excelente"],
  ["Formaldeído (HCHO) 37%", "Excelente", "Excelente", "Excelente"],
  ["Gelatina", "Excelente", "Excelente", "Excelente"],
  ["Glicose (C6H12O6)", "Excelente", "Excelente", "Excelente"],
  ["Hidrazina (N2H4) 35%", "Bom", "Excelente", "Bom"],
  ["Nitrobenzeno (C6H5NO2)", "Limitado", "Bom", "Limitado"],
  ["Sabão Líquido", "Excelente", "Excelente", "Excelente"],
  ["Silicato de Sódio (Na2SiO3)", "Excelente", "Excelente", "Excelente"],
  ["Sulfeto de Hidrogênio (H2S) Gasoso", "Excelente", "Excelente", "Excelente"],
  ["Terebintina", "Limitado", "Bom", "Limitado"],
  ["Uréia (CH4N2O) 10%", "Excelente", "Excelente", "Excelente"],
  ["Verniz", "Limitado", "Bom", "Limitado"],
] as const;

export const chemicalResistanceData: ChemicalResistanceItem[] =
  rawChemicalResistanceData.map(([substance, pvcU, cpvc, resistance]) => ({
    substance,
    pvcU,
    cpvc,
    resistance: toResistanceLevel(resistance),
  }));
